import {reactive} from 'vue'
export const iconMap = reactive({
    '00': 'icon-qing-baitian',  
    '01':'icon-yintian',
    '02':'icon-duoyun',
    '03': 'icon-zhenyu',
    '04': 'icon-leizhenyu',
    '05': 'icon-leizhenyubanyoubingbao',
    '06': 'icon-yujiaxue',
    '07': 'icon-xiaoyu',
    '08': 'icon-中雨',
    '09':'icon-dayu',
    '10': 'icon-baoyu',
    '11': 'icon-dabaoyu',
    '12':'icon-tedabaoyu',
    '13':'icon-zhenxue',
    '14':'icon-tianqi-xiaoxue',
    '15':'icon-zhongxue',
    '16': 'icon-tianqi-xiaoxue',
    '17': 'icon-baoxue1',
    '18': 'icon-wu',
    '19': 'icon-dongyu',
    '20': 'icon-shachenbao',
    '21': 'icon-zhongyu',
    '22': 'icon-dayu',
    '23':'icon-baoyu',
    '24':'icon-dabaoyu',
    '25':'icon-dtedabaoyu',
    '26':'icon-zhongxue',
    '27': 'icon-daxue',
    '28':'icon-baoxue1',
    '29':'icon-fuchen',
    '30':'icon-yangsha',
    '31':'icon-qiangshachenbao',
    '32':'icon-nongwu',
    '33':'icon-longjuanfeng',
    '34': 'icon-duoyun',
    '35': 'icon-tianqi-qingwu',
    '49': 'icon-qiangnongwu',
    '53': 'icon-mai',
    '54': 'icon-zhongduwumai1',
    '56': 'icon-yanzhongmai',
    '57':'icon-teqiangnongwu',
    '301': 'icon-xiaoyu',
    '302':'icon-xiaoxue',
    
}  )

